In [1]:
#union de dataframes

In [3]:
import pandas as pd

In [4]:
dataframe1=pd.DataFrame({'c1':['1','2','3'],'clave':['a','b','c']})
dataframe1

c1 clave
0  1     a
1  2     b
2  3     c

In [5]:
dataframe2=pd.DataFrame({'C2':['4','5','6'],'clave':['c','b','e']})
dataframe2

C2 clave
0  4     c
1  5     b
2  6     e

In [7]:
dataframe3=pd.DataFrame.merge(dataframe1,dataframe2,on='clave')
dataframe3

c1 clave C2
0  2     b  5
1  3     c  4

In [8]:
dataframe4=pd.DataFrame.merge(dataframe1,dataframe2,on='clave',how='left')
dataframe4

c1 clave   C2
0  1     a  NaN
1  2     b    5
2  3     c    4

In [9]:
dataframe5=dataframe4=pd.DataFrame.merge(dataframe1,dataframe2,on='clave',how='right')
dataframe5

c1 clave C2
0    2     b  5
1    3     c  4
2  NaN     e  6

In [10]:
dataframe5=pd.DataFrame.merge(dataframe1,dataframe2,on='clave',how='outer')
dataframe5

c1 clave   C2
0    1     a  NaN
1    2     b    5
2    3     c    4
3  NaN     e    6

In [11]:
import numpy as np

In [12]:
array1=np.arange(9).reshape(3,3)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.concatenate([array1,array1])


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.concatenate([array1,array1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [15]:
serie1=pd.Series([1,2,3],index=list('abc'))
serie1

a    1
b    2
c    3
dtype: int64

In [16]:
serie2=pd.Series([4,5,6],index=list('def'))
serie2

d    4
e    5
f    6
dtype: int64

In [17]:
pd.concat([serie1,serie2])

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [18]:
pd.concat([serie1,serie2],keys=['serie1','serie2'])


serie1  a    1
        b    2
        c    3
serie2  d    4
        e    5
        f    6
dtype: int64

In [19]:
dataframe1=pd.DataFrame(np.random.rand(3,3),columns=list('abc'))
dataframe1

a         b         c
0  0.379777  0.603893  0.065765
1  0.422222  0.399826  0.083205
2  0.861390  0.932623  0.016624

In [20]:
dataframe2=pd.DataFrame(np.random.rand(2,3),columns=list('abc'))
dataframe2

a         b         c
0  0.626384  0.480214  0.418359
1  0.643538  0.534050  0.788123

In [21]:
dataframe3=pd.concat([dataframe1,dataframe2])
dataframe3

a         b         c
0  0.379777  0.603893  0.065765
1  0.422222  0.399826  0.083205
2  0.861390  0.932623  0.016624
0  0.626384  0.480214  0.418359
1  0.643538  0.534050  0.788123

In [22]:
dataframe3=pd.concat([dataframe1,dataframe2],ignore_index=True)
dataframe3


a         b         c
0  0.379777  0.603893  0.065765
1  0.422222  0.399826  0.083205
2  0.861390  0.932623  0.016624
3  0.626384  0.480214  0.418359
4  0.643538  0.534050  0.788123

In [23]:
serie1=pd.Series([1,2,np.nan])
serie1
serie2=pd.Series([4,5,6])
serie2
serie3=serie1.combine_first(serie2)
serie3

0    1.0
1    2.0
2    6.0
dtype: float64

In [24]:
lista_valores=[1,2,np.nan]
dataframe1=pd.DataFrame(lista_valores)
dataframe1

0
0  1.0
1  2.0
2  NaN

In [25]:
lista_valores_2=[4,5,6]
dataframe_2=pd.DataFrame(lista_valores_2)
dataframe_2

0
0  4
1  5
2  6

In [26]:
dataframe_3=dataframe1.combine_first(dataframe_2)
dataframe_3

0
0  1.0
1  2.0
2  6.0

In [27]:
#eliminar duplicados en Dataframe


In [28]:
lista_valores=[[1,2],[1,2],[5,6],[5,8]]
lista_valores

[[1, 2], [1, 2], [5, 6], [5, 8]]

In [29]:
lista_indices=list('mnop')
lista_indices

['m', 'n', 'o', 'p']

In [30]:
lista_columnas=['valor1','valor2']

In [31]:
lista_columnas

['valor1', 'valor2']

In [32]:
dataframe=pd.DataFrame(lista_valores,index=lista_indices,columns=lista_columnas)
dataframe


valor1  valor2
m       1       2
n       1       2
o       5       6
p       5       8

In [34]:
dataframe2=dataframe.drop_duplicates()
dataframe2

valor1  valor2
m       1       2
o       5       6
p       5       8

In [35]:
dataframe2.drop_duplicates(['valor1'])

valor1  valor2
m       1       2
o       5       6

In [36]:
dataframe2.drop_duplicates(['valor1'],keep='last')

valor1  valor2
m       1       2
p       5       8

In [37]:
serie1=pd.Series([1,2,3,4,5],index=list('abcde'))
serie1



a    1
b    2
c    3
d    4
e    5
dtype: int64

In [38]:
serie1.replace(1,6)

a    6
b    2
c    3
d    4
e    5
dtype: int64

In [39]:
serie1=serie1.replace(1,6)

In [40]:
serie1=serie1.replace({2:8,3:9})
serie1

a    6
b    8
c    9
d    4
e    5
dtype: int64

In [41]:
lista_valores=np.arange(9).reshape(3,3)
lista_valores

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
lista_indices=list('abc')
lista_indices

['a', 'b', 'c']

In [57]:
dataframe=pd.DataFrame(lista_valores,index=lista_indices)
dataframe

0  1  2
a  0  1  2
b  3  4  5
c  6  7  8

In [45]:
nuevos_indices=dataframe.index.map(str.upper)
dataframe.index=nuevos_indices

In [46]:
dataframe

0  1  2
A  0  1  2
B  3  4  5
C  6  7  8

In [47]:
dataframe=dataframe.rename(index=str.lower)
dataframe

0  1  2
a  0  1  2
b  3  4  5
c  6  7  8

In [56]:
dataframe

In [62]:
nuevos_indices={'b':'j'}
dataframe.rename(index=nuevos_indices,inplace=True)


In [63]:
dataframe

0  1  2
a  0  1  2
j  3  4  5
c  6  7  8

In [1]:
#Agrupar datos en categorias

In [5]:
import numpy as np
import pandas as pd

In [6]:
precios=[45,34,48,24,53,21,88,34,26]
rango=[10,20,30,40,50,60,70,80,90,100]


In [7]:
precio_con_rango=pd.cut(precios,rango)

In [8]:
precio_con_rango

[(40, 50], (30, 40], (40, 50], (20, 30], (50, 60], (20, 30], (80, 90], (30, 40], (20, 30]]
Categories (9, interval[int64]): [(10, 20] < (20, 30] < (30, 40] < (40, 50] ... (60, 70] < (70, 80] < (80, 90] < (90, 100]]

In [9]:
pd.value_counts(precio_con_rango)

(20, 30]     3
(40, 50]     2
(30, 40]     2
(80, 90]     1
(50, 60]     1
(90, 100]    0
(70, 80]     0
(60, 70]     0
(10, 20]     0
dtype: int64

In [10]:
lista_valores=np.random.rand(10,3)
lista_valores


array([[0.82716916, 0.4429862 , 0.87218935],
       [0.96529694, 0.15310332, 0.83927584],
       [0.96243533, 0.71501653, 0.05017489],
       [0.85112413, 0.50240485, 0.56117249],
       [0.43553814, 0.65553724, 0.18517897],
       [0.89326531, 0.28797571, 0.37101932],
       [0.29179572, 0.90094789, 0.28224535],
       [0.06631736, 0.46964276, 0.83221966],
       [0.10361086, 0.95460843, 0.22664974],
       [0.42644919, 0.72193113, 0.48891791]])

In [11]:
dataframe=pd.DataFrame(lista_valores)
dataframe

0         1         2
0  0.827169  0.442986  0.872189
1  0.965297  0.153103  0.839276
2  0.962435  0.715017  0.050175
3  0.851124  0.502405  0.561172
4  0.435538  0.655537  0.185179
5  0.893265  0.287976  0.371019
6  0.291796  0.900948  0.282245
7  0.066317  0.469643  0.832220
8  0.103611  0.954608  0.226650
9  0.426449  0.721931  0.488918

In [12]:
dataframe[0]

0    0.827169
1    0.965297
2    0.962435
3    0.851124
4    0.435538
5    0.893265
6    0.291796
7    0.066317
8    0.103611
9    0.426449
Name: 0, dtype: float64

In [13]:
columna=dataframe[0]

In [14]:
columna

0    0.827169
1    0.965297
2    0.962435
3    0.851124
4    0.435538
5    0.893265
6    0.291796
7    0.066317
8    0.103611
9    0.426449
Name: 0, dtype: float64

In [15]:
columna[columna>0.40]

0    0.827169
1    0.965297
2    0.962435
3    0.851124
4    0.435538
5    0.893265
9    0.426449
Name: 0, dtype: float64

In [16]:
dataframe

0         1         2
0  0.827169  0.442986  0.872189
1  0.965297  0.153103  0.839276
2  0.962435  0.715017  0.050175
3  0.851124  0.502405  0.561172
4  0.435538  0.655537  0.185179
5  0.893265  0.287976  0.371019
6  0.291796  0.900948  0.282245
7  0.066317  0.469643  0.832220
8  0.103611  0.954608  0.226650
9  0.426449  0.721931  0.488918

In [17]:
dataframe[dataframe>0.40]

0         1         2
0  0.827169  0.442986  0.872189
1  0.965297       NaN  0.839276
2  0.962435  0.715017       NaN
3  0.851124  0.502405  0.561172
4  0.435538  0.655537       NaN
5  0.893265       NaN       NaN
6       NaN  0.900948       NaN
7       NaN  0.469643  0.832220
8       NaN  0.954608       NaN
9  0.426449  0.721931  0.488918

In [18]:
#combinacion de elementos

In [19]:
lista_valores=np.arange(25).reshape(5,5)
lista_valores

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
dataframe=pd.DataFrame(lista_valores)
dataframe

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [21]:
combinacion_aleatoria=np.random.permutation(5)
combinacion_aleatoria

array([0, 1, 2, 4, 3])

In [22]:
dataframe.take(combinacion_aleatoria)

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
4  20  21  22  23  24
3  15  16  17  18  19

In [23]:
#agrupacion de dataframe

In [26]:
lista_valores={'clave1':['x','x','y','y','s'],'clave2':['a','b','a','c','d'],'datos1':np.random.rand(5),'datos2':np.random.rand(5)}
lista_valores

{'clave1': ['x', 'x', 'y', 'y', 's'],
 'clave2': ['a', 'b', 'a', 'c', 'd'],
 'datos1': array([0.95543929, 0.79952959, 0.82739006, 0.11227141, 0.6302923 ]),
 'datos2': array([0.2109005 , 0.23876658, 0.53761721, 0.14412765, 0.634189  ])}

In [27]:
dataframe=pd.DataFrame(lista_valores)
dataframe

clave1 clave2    datos1    datos2
0      x      a  0.955439  0.210901
1      x      b  0.799530  0.238767
2      y      a  0.827390  0.537617
3      y      c  0.112271  0.144128
4      s      d  0.630292  0.634189

In [30]:
grupo1=dataframe['datos1'].groupby(dataframe['clave1'])

In [31]:
grupo1

In [32]:
grupo1.mean()

clave1
s    0.630292
x    0.877484
y    0.469831
Name: datos1, dtype: float64

In [ ]:
# agrupacion (operacion que dan un valor  ,como la media)

In [35]:
lista_valores=[[1,2,3],[4,5,6],[7,8,9],[np.nan,np.nan,np.nan]]
lista_valores

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [nan, nan, nan]]

In [36]:
lista_columnas=list('abc')
lista_columnas

['a', 'b', 'c']

In [37]:
dataframe=pd.DataFrame(lista_valores,columns=lista_columnas)
dataframe

a    b    c
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [38]:
dataframe.agg(['sum','min'])

a     b     c
sum  12.0  15.0  18.0
min   1.0   2.0   3.0

In [40]:
dataframe.agg('sum',axis=1)

0     6.0
1    15.0
2    24.0
3     0.0
dtype: float64