In [1]:
# Series

In [2]:
import pandas as pd

In [3]:
serie1=pd.Series([3,5,7])
serie1

0    3
1    5
2    7
dtype: int64

In [4]:
serie1[1]

5

In [6]:
asignaturas=['matematicas','historia','fisica','literatura']
notas=[8,6,9,7]
serie_notas_daniel=pd.Series(notas,index=asignaturas)

In [7]:
serie_notas_daniel

matematicas    8
historia       6
fisica         9
literatura     7
dtype: int64

In [8]:
serie_notas_daniel['fisica']

9

In [9]:
serie_notas_daniel[serie_notas_daniel>=8]

matematicas    8
fisica         9
dtype: int64

In [11]:
serie_notas_daniel.name='notas de Daniel'

In [12]:
serie_notas_daniel

matematicas    8
historia       6
fisica         9
literatura     7
Name: notas de Daniel, dtype: int64

In [13]:
serie_notas_daniel.index.name='las asignaturas de daniel'

In [14]:
serie_notas_daniel

las asignaturas de daniel
matematicas    8
historia       6
fisica         9
literatura     7
Name: notas de Daniel, dtype: int64

In [15]:
diccionario=serie_notas_daniel.to_dict()

In [16]:
diccionario

{'matematicas': 8, 'historia': 6, 'fisica': 9, 'literatura': 7}

In [17]:
serie=pd.Series(diccionario)


In [18]:
serie

matematicas    8
historia       6
fisica         9
literatura     7
dtype: int64

In [19]:
serie

matematicas    8
historia       6
fisica         9
literatura     7
dtype: int64

In [20]:
serie_notas_daniel

las asignaturas de daniel
matematicas    8
historia       6
fisica         9
literatura     7
Name: notas de Daniel, dtype: int64

In [22]:
notas_ana=[8,5,7,9]
serie_notas_ana=pd.Series(notas_ana,index=asignaturas)
serie_notas_ana

matematicas    8
historia       5
fisica         7
literatura     9
dtype: int64

In [23]:
serie_notas_clase=(serie_notas_ana+serie_notas_daniel)/2

In [24]:
serie_notas_clase

matematicas    8.0
historia       5.5
fisica         8.0
literatura     8.0
dtype: float64

In [ ]:
#Dataframes

In [26]:
import webbrowser
website='https://es.wikipedia.org/wiki/Anexo:Campeones_de_la_NBA'
webbrowser.open(website)

True

In [34]:
dataframe_nba=pd.read_clipboard()

In [35]:
dataframe_nba

Año      Campeón       del    Oeste Resultado     Campeón.1       del.1  \
0   1950  Minneapolis  Lakersn.       2​       4–2      Syracuse  Nationals†   
1   1951    Rochester    Royals      4–3       New          York      Knicks   
2   1952  Minneapolis    Lakers      4–3       New          York      Knicks   
3   1953  Minneapolis   Lakers†      4–1       New          York      Knicks   
4   1954  Minneapolis   Lakers†      4–3  Syracuse     Nationals         23​   
5   1955          Ft.     Wayne  Pistons       3–4      Syracuse  Nationals†   
6   1956          Ft.     Wayne  Pistons       1–4  Philadelphia   Warriors†   
7   1957          St.     Louis    Hawks       3–4        Boston    Celtics†   
8   1958          St.     Louis    Hawks       4–2        Boston    Celtics†   
9   1959  Minneapolis    Lakers      0–4    Boston      Celtics†         28​   
10  1960          St.     Louis    Hawks       3–4        Boston    Celtics†   
11  1961          St.     Louis    Hawks       1–4        Boston    Celtics†   
12  1962          Los   Angeles   Lakers       3–4        Boston    Celtics†   
13  1963          Los   Angeles   Lakers       2–4        Boston    Celtics†   

      Este  Ref.  
0   19​18​   NaN  
1      20​   NaN  
2      21​   NaN  
3      22​   NaN  
4     None   NaN  
5      24​   NaN  
6      25​   NaN  
7      26​   NaN  
8      27​   NaN  
9     None   NaN  
10     29​   NaN  
11     30​   NaN  
12     31​   NaN  
13     32​   NaN

In [29]:
dataframe_nba.columns

Index(['Año', 'Campeón', 'del', 'Oeste', 'Resultado', 'Campeón.1', 'del.1',
       'Este', 'Ref.'],
      dtype='object')

In [36]:
dataframe_nba['Campeón']

0     Minneapolis
1       Rochester
2     Minneapolis
3     Minneapolis
4     Minneapolis
5             Ft.
6             Ft.
7             St.
8             St.
9     Minneapolis
10            St.
11            St.
12            Los
13            Los
Name: Campeón, dtype: object

In [37]:
dataframe_nba.loc[5]

Año                1955
Campeón             Ft.
del               Wayne
Oeste           Pistons
Resultado           3–4
Campeón.1      Syracuse
del.1        Nationals†
Este                24​
Ref.                NaN
Name: 5, dtype: object

In [38]:
dataframe_nba.head()

Año      Campeón       del Oeste Resultado  Campeón.1       del.1    Este  \
0  1950  Minneapolis  Lakersn.    2​       4–2   Syracuse  Nationals†  19​18​   
1  1951    Rochester    Royals   4–3       New       York      Knicks     20​   
2  1952  Minneapolis    Lakers   4–3       New       York      Knicks     21​   
3  1953  Minneapolis   Lakers†   4–1       New       York      Knicks     22​   
4  1954  Minneapolis   Lakers†   4–3  Syracuse  Nationals         23​    None   

   Ref.  
0   NaN  
1   NaN  
2   NaN  
3   NaN  
4   NaN

In [39]:
dataframe_nba.head(3)

Año      Campeón       del Oeste Resultado Campeón.1       del.1    Este  \
0  1950  Minneapolis  Lakersn.    2​       4–2  Syracuse  Nationals†  19​18​   
1  1951    Rochester    Royals   4–3       New      York      Knicks     20​   
2  1952  Minneapolis    Lakers   4–3       New      York      Knicks     21​   

   Ref.  
0   NaN  
1   NaN  
2   NaN

In [40]:
dataframe_nba.tail()

Año      Campeón      del   Oeste Resultado Campeón.1     del.1  Este  \
9   1959  Minneapolis   Lakers     0–4    Boston  Celtics†       28​  None   
10  1960          St.    Louis   Hawks       3–4    Boston  Celtics†   29​   
11  1961          St.    Louis   Hawks       1–4    Boston  Celtics†   30​   
12  1962          Los  Angeles  Lakers       3–4    Boston  Celtics†   31​   
13  1963          Los  Angeles  Lakers       2–4    Boston  Celtics†   32​   

    Ref.  
9    NaN  
10   NaN  
11   NaN  
12   NaN  
13   NaN

In [41]:
lista_asiganaturas=['matematicas','historia','fisica']
lista_notas=[7,8,9]
diccionario={'Asiganturas':lista_asiganaturas,'Notas':lista_notas}

In [42]:
diccionario

{'Asiganturas': ['matematicas', 'historia', 'fisica'], 'Notas': [7, 8, 9]}

In [43]:
dataframe_notas=pd.DataFrame(diccionario)

In [44]:
dataframe_notas

Asiganturas  Notas
0  matematicas      7
1     historia      8
2       fisica      9

In [ ]:
#indices

In [46]:
lista_valores=[1,2,3]
lista_indices=['a','b','c']
serie=pd.Series(lista_valores,index=lista_indices)

In [47]:
serie

a    1
b    2
c    3
dtype: int64

In [48]:
serie.index

Index(['a', 'b', 'c'], dtype='object')

In [49]:
serie.index[0]

'a'

In [50]:
serie.index[0]='z'

TypeError: Index does not support mutable operations

In [51]:
lista_valores=[[6,7,8],[8,9,5],[6,5,7]]

In [53]:
lista_indices=['matematicas','historia','fisica']
lista_nombre=['Antonio','Maria','Pedro']


In [54]:
dataframe=pd.DataFrame(lista_valores,index=lista_indices,columns=lista_nombre)

In [55]:
dataframe

Antonio  Maria  Pedro
matematicas        6      7      8
historia           8      9      5
fisica             6      5      7

In [56]:
dataframe.index

Index(['matematicas', 'historia', 'fisica'], dtype='object')

In [57]:
dataframe.index[1]

'historia'

In [59]:
#eliminar elementos  en series y dataframes

In [60]:
import numpy as np

In [61]:
np.arange(3)

array([0, 1, 2])

In [62]:
serie=pd.Series(np.arange(4),index=['a','b','c','d'])

In [63]:
serie

a    0
b    1
c    2
d    3
dtype: int32

In [64]:
serie.drop('c')

a    0
b    1
d    3
dtype: int32

In [65]:
np.arange(9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
lista_valores=np.arange(9).reshape(3,3)

In [68]:
lista_indices=['a','b','c']
lista_columnas=['c1','c2','c3']
dataframe=pd.DataFrame(lista_valores,index=lista_indices,columns=lista_columnas)
dataframe

c1  c2  c3
a   0   1   2
b   3   4   5
c   6   7   8

In [69]:
dataframe.drop('b')

c1  c2  c3
a   0   1   2
c   6   7   8

In [70]:
dataframe.drop('c2',axis=1)

c1  c3
a   0   2
b   3   5
c   6   8

In [71]:
dataframe=dataframe.drop('b')

In [72]:
dataframe

c1  c2  c3
a   0   1   2
c   6   7   8

In [73]:
#seleccionar datos en las series

In [74]:
lista_valores=np.arange(3)
lista_valores

array([0, 1, 2])

In [75]:
lista_indices=['i1','i2','i3']

In [77]:
serie=pd.Series(lista_valores,index=lista_indices)

In [78]:
serie

i1    0
i2    1
i3    2
dtype: int32

In [79]:
serie=serie*2

In [80]:
serie

i1    0
i2    2
i3    4
dtype: int32

In [81]:
serie['i2']

2

In [83]:
serie[2]

4

In [85]:
serie[0:3]

i1    0
i2    2
i3    4
dtype: int32

In [86]:
serie['i1':'i3']

i1    0
i2    2
i3    4
dtype: int32

In [87]:
serie[serie>3]

i3    4
dtype: int32

In [88]:
serie[serie>3]=6

In [89]:
serie

i1    0
i2    2
i3    6
dtype: int32

In [90]:
#seleccionando entradas para Dataframes

In [91]:
lista_valores=np.arange(25).reshape(5,5)
lista_valores

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [92]:
lista_indices=['i1','i2','i3','i4','i5']

In [93]:
lista_columnas=['c1','c2','c3','c4','c5']

In [94]:
dataframe=pd.DataFrame(lista_valores,index=lista_indices,columns=lista_columnas)
dataframe

c1  c2  c3  c4  c5
i1   0   1   2   3   4
i2   5   6   7   8   9
i3  10  11  12  13  14
i4  15  16  17  18  19
i5  20  21  22  23  24

In [95]:
dataframe['c2']

i1     1
i2     6
i3    11
i4    16
i5    21
Name: c2, dtype: int32

In [96]:
dataframe['c2']['i2']

6

In [97]:
dataframe[['c3','c4']]

c3  c4
i1   2   3
i2   7   8
i3  12  13
i4  17  18
i5  22  23

In [99]:
dataframe[['c2','c4','c3']]

c2  c4  c3
i1   1   3   2
i2   6   8   7
i3  11  13  12
i4  16  18  17
i5  21  23  22

In [100]:
dataframe[dataframe['c2']>15]

c1  c2  c3  c4  c5
i4  15  16  17  18  19
i5  20  21  22  23  24

In [101]:
dataframe>20

c1     c2     c3     c4     c5
i1  False  False  False  False  False
i2  False  False  False  False  False
i3  False  False  False  False  False
i4  False  False  False  False  False
i5  False   True   True   True   True

In [102]:
dataframe.loc['i3']

c1    10
c2    11
c3    12
c4    13
c5    14
Name: i3, dtype: int32

In [103]:
dataframe.loc['i3']['c4']

13

In [ ]:
#Operaciones sobre series y dataframes

In [105]:
serie1=pd.Series([0,1,2],index=['a','b','c'])
serie1

a    0
b    1
c    2
dtype: int64

In [106]:
serie2=pd.Series([3,4,5,6],index=['a','b','c','d'])
serie2

a    3
b    4
c    5
d    6
dtype: int64

In [107]:
serie1+serie2

a    3.0
b    5.0
c    7.0
d    NaN
dtype: float64

In [108]:
lista_valores=np.arange(4).reshape(2,2)
lista_valores

array([[0, 1],
       [2, 3]])

In [109]:
lista_indices=list('ab')
lista_indices

['a', 'b']

In [110]:
lista_columnas=list('12')
lista_columnas

['1', '2']

In [111]:
dataframe=pd.DataFrame(lista_valores,index=lista_indices,columns=lista_columnas)
dataframe

1  2
a  0  1
b  2  3

In [112]:
lista_valores_2=np.arange(9).reshape(3,3)
lista_valores_2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [113]:
lista_indices_2=list('abc')
lista_columnas_2=list('123')

In [114]:
dataframe2=pd.DataFrame(lista_valores_2,index=lista_indices_2,columns=lista_columnas_2)
dataframe2

1  2  3
a  0  1  2
b  3  4  5
c  6  7  8

In [116]:
dataframe3=dataframe+dataframe2

In [119]:
dataframe.add(dataframe2,fill_value=0)

1    2    3
a  0.0  2.0  2.0
b  5.0  7.0  5.0
c  6.0  7.0  8.0

In [ ]:
#ordenar y clasificar series

In [120]:
range(4)

range(0, 4)

In [123]:
lista_valores=range(4)


In [124]:
lista_indices=list('CABD')
lista_indices

['C', 'A', 'B', 'D']

In [125]:
serie=pd.Series(lista_valores,index=lista_indices)

In [126]:
serie

C    0
A    1
B    2
D    3
dtype: int64

In [127]:
serie.sort_index()

A    1
B    2
C    0
D    3
dtype: int64

In [128]:
serie.sort_values()

C    0
A    1
B    2
D    3
dtype: int64

In [129]:
serie.rank()

C    1.0
A    2.0
B    3.0
D    4.0
dtype: float64

In [130]:
serie2=pd.Series(np.random.randn(10))
serie2

0    1.777681
1    1.653844
2   -1.707090
3    2.202146
4    0.404760
5    0.285793
6   -0.638214
7    0.104319
8    0.001293
9   -1.139922
dtype: float64

In [131]:
serie2.rank()

0     9.0
1     8.0
2     1.0
3    10.0
4     7.0
5     6.0
6     3.0
7     5.0
8     4.0
9     2.0
dtype: float64

In [132]:
serie2.sort_values()

2   -1.707090
9   -1.139922
6   -0.638214
8    0.001293
7    0.104319
5    0.285793
4    0.404760
1    1.653844
0    1.777681
3    2.202146
dtype: float64

In [ ]:
#Estadisticas en dataframes

In [133]:
array=np.array([[1,8,3],[5,6,7]])
array

array([[1, 8, 3],
       [5, 6, 7]])

In [135]:
dataframe=pd.DataFrame(array,index=['a','b'],columns=list('123'))
dataframe

1  2  3
a  1  8  3
b  5  6  7

In [136]:
dataframe.sum()

1     6
2    14
3    10
dtype: int64

In [137]:
dataframe.sum(axis=1)


a    12
b    18
dtype: int64

In [138]:
dataframe.min()

1    1
2    6
3    3
dtype: int32

In [139]:
dataframe.max()

1    5
2    8
3    7
dtype: int32

In [140]:
dataframe.max(axis=1)

a    8
b    7
dtype: int32

In [141]:
dataframe.idxmin()

1    a
2    b
3    a
dtype: object

In [142]:
dataframe

1  2  3
a  1  8  3
b  5  6  7

In [143]:
dataframe.describe()

1         2         3
count  2.000000  2.000000  2.000000
mean   3.000000  7.000000  5.000000
std    2.828427  1.414214  2.828427
min    1.000000  6.000000  3.000000
25%    2.000000  6.500000  4.000000
50%    3.000000  7.000000  5.000000
75%    4.000000  7.500000  6.000000
max    5.000000  8.000000  7.000000

In [ ]:
#valores nulos -NaN

In [144]:
lista_valores=['1','2',np.nan,'4']
lista_valores

['1', '2', nan, '4']

In [145]:
serie=pd.Series(lista_valores,index=list('abcd'))

In [146]:
serie


a      1
b      2
c    NaN
d      4
dtype: object

In [148]:
serie.isnull()

a    False
b    False
c     True
d    False
dtype: bool

In [149]:
serie.dropna()

a    1
b    2
d    4
dtype: object

In [150]:
serie=serie.dropna()

In [151]:
serie

a    1
b    2
d    4
dtype: object

In [152]:
lista_valores=[[1,2,3],[4,np.nan,5],[6,7,np.nan]]
lista_valores

[[1, 2, 3], [4, nan, 5], [6, 7, nan]]

In [153]:
lista_indices=list('123')
lista_indices

['1', '2', '3']

In [154]:
lista_columnas=list('abc')
lista_columnas

['a', 'b', 'c']

In [156]:
dataframe=pd.DataFrame(lista_valores,index=lista_indices,columns=lista_columnas)
dataframe

a    b    c
1  1  2.0  3.0
2  4  NaN  5.0
3  6  7.0  NaN

In [157]:
dataframe.isnull()

a      b      c
1  False  False  False
2  False   True  False
3  False  False   True

In [158]:
dataframe.dropna()

a    b    c
1  1  2.0  3.0

In [159]:
dataframe.fillna(0)

a    b    c
1  1  2.0  3.0
2  4  0.0  5.0
3  6  7.0  0.0

In [ ]:
#jerarquia en los indices

In [160]:
lista_valores=np.random.rand(6)
lista_valores

array([0.17196067, 0.95208786, 0.85631053, 0.88960267, 0.53327736,
       0.70168786])

In [161]:
lista_indices=[[1,1,1,2,2,2],['a','b','c','a','b','c']]
lista_indices

[[1, 1, 1, 2, 2, 2], ['a', 'b', 'c', 'a', 'b', 'c']]

In [162]:
series=pd.Series(lista_valores,index=lista_indices)
series

1  a    0.171961
   b    0.952088
   c    0.856311
2  a    0.889603
   b    0.533277
   c    0.701688
dtype: float64

In [163]:
series[1]

a    0.171961
b    0.952088
c    0.856311
dtype: float64

In [164]:
series[1]['b']

0.9520878567311086

In [165]:
dataframe=series.unstack()

In [166]:
dataframe

a         b         c
1  0.171961  0.952088  0.856311
2  0.889603  0.533277  0.701688

In [167]:
lista_valores=np.arange(16).reshape(4,4)
lista_valores

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [168]:
lista_indices=list('1234')
lista_indices

['1', '2', '3', '4']

In [169]:
lista_columnas=list('abcd')
lista_columnas

['a', 'b', 'c', 'd']

In [170]:
dataframe2=pd.DataFrame(lista_valores,index=lista_indices,columns=lista_columnas)
dataframe2

a   b   c   d
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15

In [171]:
serie2=dataframe2.stack()
serie2

1  a     0
   b     1
   c     2
   d     3
2  a     4
   b     5
   c     6
   d     7
3  a     8
   b     9
   c    10
   d    11
4  a    12
   b    13
   c    14
   d    15
dtype: int32